### PR TITLE
🐳 created kf vcf2maf docker

### PR DESCRIPTION
**Pull request by migbro**
## Description

Created a docker to pull our modified vcf2maf repo and build

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Build docker
- [ ] `Start interactive docker: docker run -it --volume $PWD/:/WORK <build_name>`
- [ ] Ran command `perl /opt/vcf2maf.pl --input-vcf BS_M5FM63EB.consensus.PASS.vep.vcf --output-maf updated_output2.maf --use-kf-fields --tumor-id BS_M5FM63EB --normal-id BS_9H6Z0MEG --custom-enst /opt/data/isoform_overrides_uniprot --ref-fasta Homo_sapiens_assembly38.fasta --retain-info MQ,MQ0,CAL,Hotspot`

**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have committed any related changes to the PR

### CODE REVIEW

**Comment by dmiller15** [comment]
Rebase pls

**Comment by migbro** [comment]
I just realized I also need to add this docker to the circle ci config, as well as the VEP one I had merged. I will try to do that this afternoon.

**Comment by migbro** [comment]
> Rebase pls

Done!

**Review by dmiller15 — APPROVED** [review]
So do we prefer ENTRYPOINT or CMD for those last commands in the docker?

**Comment by migbro** [comment]
> So do we prefer ENTRYPOINT or CMD for those last commands in the docker?

Oh, interesting, I used entrypoint just because i wanted it to be in a shell when i run interactively. I didn't give a second thought to `CMD`

**Review by sickler-alex — APPROVED** [review]

**Comment by migbro** [comment]
Approving after comments from SBG. This is technically a working docker, but fails on cavatica. SBG user support has this to say:
>The issue seems to be related to the docker image configuration, but can't be sure what exactly. SBG executor runs all docker images as user root, however the logs show that there was an error running this image with the message (docker: Error response from daemon: unable to find user root: no matching entries in passwd file.). If there was some step in docker build related to user management in docker, we suggest removing that and trying again.

I have attempted to figure out how to add a user to /etc/passwd but have had no luck. I will try using the usual ubuntu instead of clearlinux

**Pull request merged**
