### PR TITLE
🚀 Add cell ranger v6.1.2

### PR DESCRIPTION
**Pull request by migbro**
## Description

Unfortunately, will be doomed to fail over time as it requires token, but will likely stay alive long enough for this PR.
Has bug fixes that makes CR v6 work better

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Build local
- [ ] Run in various cavatica tasks

**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have committed any related changes to the PR

### CODE REVIEW

**Comment by dmiller15** [comment]
This needs to be rebased or just remade entirely with only the changes.

**Comment by migbro** [comment]
> This needs to be rebased or just remade entirely with only the pertinent changes.

Yeah, that's the thing. I did `git rebase master` since this is a bit of an old branch, and it did...that. Not sure why...

**Comment by dmiller15** [comment]
Idk. Probably just delete the branch and make a new one off of master. There's no need to preserve any commit history for a new dockerfile.

**Review by sakshamphul — APPROVED** [review]

**Comment by migbro** [comment]
> Fixed it

Thanks!

**Review by dmiller15 — APPROVED** [review]

**Pull request merged**
