### PR TITLE
⏫Mb update vcf2maf1.0.2

### PR DESCRIPTION
**Pull request by migbro**
## Description

This incorporates updates from [this PR](https://github.com/kids-first/kf-mskcc-vcf2maf/pull/4) where large file inputs failed.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Built and ran locally, simple script + help test ( `docker run -it migbro/vcf2maf:v1.0.2`, `perl vcf2maf/vcf2maf.pl -h`
- [ ] Test B

**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have committed any related changes to the PR

### CODE REVIEW

**Review by mark-welsh — APPROVED** [review]
the docker built fine so approving it. any reason the consensus merge docker is being removed as part of this PR?

**Review by dmiller15 — APPROVED** [review]
Same question as Mark about the consensus merge stuff.

**Comment by migbro** [comment]
As far as I know, it's not actually being removed. It's a weird quirk of the make config script where it deleted it, then recreated it further down. If this isn't what I think happened please tell me!!!

**Comment by mark-welsh** [comment]
true it looks like everything is still there 👍  I wonder how it was changed

**Pull request merged**
