### PR TITLE
✨ Nhj theta2 docker

### PR DESCRIPTION
**Pull request by NHJohnson**
## Description

This creates versions for the THetA2 Dockerfile and adds one for THetA2 0.7.1, which is the release in the KF version with the performance improvements. Also added to circleci config. 

Fixes https://github.com/d3b-center/bixu-tracker/issues/1053

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Dockerfile builds on EC2 instance

**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings
- [X] I have committed any related changes to the PR

### CODE REVIEW

**Review by sickler-alex — CHANGES_REQUESTED** [review]
Add the Dockerfile to the image to the end of the Dockerfile. `add Dockerfile .`

**Comment by NHJohnson** [comment]
Like so?

**Review by migbro — CHANGES_REQUESTED** [review]
Hmmm, the docker builds, but when I run the theta command with just a help:
```
/THetA/bin/RunTHetA -h
Traceback (most recent call last):
  File "/THetA/bin/../python/RunTHetA.py", line 48, in <module>
    from ClusteringBAF import clustering_BAF, group_to_meta_interval
  File "/THetA/python/ClusteringBAF.py", line 38, in <module>
    import bnpy
ImportError: No module named bnpy
```
Which is weird, because I see the command execute...
I am also recommending maybe a little package cleanup to make this a little smaller, I'll follow up in the comments

**Comment by migbro** [comment]
I also recommend adding:
```apt remove -y git curl ant python-pip && apt autoremove -y && apt autoclean -y```
To reduce the image a lil bit, but this won't fix that last git repo not making it in. It's really weird!

**Comment by migbro** [comment]
Actually, I figured it out, it's a by product of removing the `RUN` (which I approve of!) and making it all one long arg. You're in a different for that last git command, so just need to `cd /` to be back in the right place for that.

**Comment by NHJohnson** [comment]
Good notes, with this change I was able to get the RunThetA help.

**Review by migbro — APPROVED** [review]
Looks good, thanks!

**Review by sickler-alex — APPROVED** [review]

**Pull request merged**
