### PR TITLE
Change PyPy image

### PR DESCRIPTION
**Pull request by sakshamphul**
## Description

This PR changes PyPy base image that was merged previously. We encountered an error while running the code with this image. 

Fixes # (issue)

Change the base image to PyPy:3

## Type of change

Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

- [x] Test A :This image was tested on EC2 instance. I do not see previous error while I test our molecular sub-typing code

**Test Configuration**:
* Environment: ubuntu and PyPy:3 base image
* Test files: None

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have committed any related changes to the PR

### CODE REVIEW

**Comment by dmiller15** [comment]
Seems like the circleci config file got jumbled here. Can you revert that change?

**Comment by migbro** [comment]
> Seems like the circleci config file got jumbled here. Can you revert that change?

As a hint, I think there is a difference as to how the output is ordered if you run the script on your local mac vs linux. Perhaps try reverting, then running it again on your local machine @sakshamphul

**Review by dmiller15 — APPROVED** [review]

**Review by migbro — APPROVED** [review]
Looks good!

**Comment by sakshamphul** [comment]
Set PyPy base image to 3

**Pull request merged**
